services:
  api:
    build:
      context: .
      dockerfile: TravelAgencyApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db4free.net;Database=travelagencydb;User=grrr_human;Password=1234567890;
    networks:
      - backend
    ports:
      - "5000:80"

  client:
    build:
      context: ./svelte-app
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - backend
    ports:
      - "3000:80"

networks:
  backend: