version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "KcvgwVMrqi"
      MYSQL_DATABASE: "sql8715683"
      MYSQL_USER: "sql8715683"
      MYSQL_PASSWORD: "KcvgwVMrqi"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: TravelAgencyApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql8.freemysqlhosting.net;Database=sql8715683;User=sql8715683;Password=KcvgwVMrqi;
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "5000:80"

  client:
    build:
      context: ./svelte-app
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:

networks:
  backend: